logger: # 日志器
  format: json # 日志格式 [json, text]
  appName: honey_node # 应用名称
  level: info # 日志级别

system: # 系统路由
  grpcManageAddr: "192.168.5.1:8081" # gRPC管理服务监听地址
  network: ens33 # 网卡名称
  uid: dde9b8cc-08b4-4f17-8c8e-209e0504a2eb # 节点唯一标识（UUID）

filterNetworkList: # 网卡过滤列表
  - br- # 过滤前缀为br-的网卡
  - docker # 过滤前缀为docker的网卡
  - mc_ # 过滤前缀为mc_的网卡
  - veth # 过滤前缀为veth的网卡
  - lo # 过滤lo网卡

mq: # rabbitMQ
  user: admin # 用户名
  password: password # 密码
  host: 192.168.5.130 # 主机地址
  port: 5672 # 端口
  createIpExchangeName: createIpExchange # 创建IP的交换机名称
  deleteIpExchangeName: deleteIpExchangeName # 删除IP的交换机名称
  bindPortExchangeName: bindPortExchangeName # 绑定端口的交换机名称
  ssl: false # 是否使用SSL
  clientCertificate: # 客户端的证书
  clientKey:  # 客户端的私钥
  caCertificate:  # ca的证书