logger: # 日志器
  format: json # 日志格式 [json, text]
  appName: honey_node # 应用名称
  level: info # 日志级别

system: # 系统路由
  grpcManageAddr: "192.168.5.130:8082" # gRPC管理服务监听地址
  network: ens33 # 网卡名称
  uid: dde9b8cc-08b4-4f17-8c8e-209e0504a2eb # 节点唯一标识（UUID）
  evePath: deploy/suricata/logs/eve.json # Suricata日志路径

filterNetworkList: # 网卡过滤列表
  - br- # 过滤前缀为br-的网卡
  - docker # 过滤前缀为docker的网卡
  - mc_ # 过滤前缀为mc_的网卡
  - veth # 过滤前缀为veth的网卡
  - lo # 过滤lo网卡

mq: # rabbitMQ
  user: admin # 用户名
  password: password # 密码
  host: 192.168.5.130 # 主机地址
  port: 5671 # 端口
  createIpExchangeName: createIpExchange # 创建IP的交换机名称
  deleteIpExchangeName: deleteIpExchangeName # 删除IP的交换机名称
  bindPortExchangeName: bindPortExchangeName # 绑定端口的交换机名称
  ssl: true # 是否使用SSL
  clientCertificate: mq_cert/client_certificate.pem # 客户端的证书
  clientKey: mq_cert/client_key.pem  # 客户端的私钥
  caCertificate: mq_cert/ca_certificate.pem  # ca的证书
  alertTopic: alertTopic # 告警Topic名称
  batchDeployExchangeName: batchDeployExchangeName # 批量部署的交换机名称
  batchDeployStatusTopic: batchDeployStatusTopic # 批量部署状态Topic名称
  batchUpdateDeployExchangeName: batchUpdateDeployExchangeName # 批量更新部署的交换机名称
  batchUpdateDeployStatusTopic: batchUpdateDeployStatusTopic # 批量更新部署状态Topic名称
  batchRemoveDeployExchangeName: batchRemoveDeployExchangeName # 批量删除部署的交换机名称
  batchRemoveDeployStatusTopic: batchRemoveDeployStatusTopic # 批量删除部署状态Topic名称

db: # SQLite数据库配置
  db_name: "gorm.db" #  数据库名称
  maxIdleConns: 10 # 最大空闲连接数
  maxOpenConns: 100 # 最大连接数
  connMaxLifetime: 10000 # 连接最大生命周期