logger: # 日志器
  format: json # 日志格式 [json, text]
  appName: honey_node # 应用名称
  level: info # 日志级别

system: # 系统路由
  grpcManageAddr: "192.168.5.1:8081" # gRPC管理服务监听地址
  network: ens33 # 网卡名称
  uid: dde9b8cc-08b4-4f17-8c8e-209e0504a2eb # 节点唯一标识（UUID）